const LOGO_URL = 'https://raw.githubusercontent.com/takashi-aoki-ybp/eps-corporate/main/logo.jpeg';
const SITE_HEADER = `
<header><div class="container"><a href="index.html" class="logo"><img src="${LOGO_URL}" alt="Enjin Payment Service"></a><nav><ul><li><a href="index.html">ホーム</a></li><li><a href="about.html">私たちについて</a></li><li><a href="services.html">サービス</a></li><li><a href="company.html">会社情報</a></li><li><a href="security.html">安心への取り組み</a></li></ul></nav><div class="header-right"><div class="header-phone"><div><div class="phone-num">03-XXXX-XXXX</div><div class="phone-hours">平日 10:00～18:30</div></div></div><a href="contact.html" class="cta-btn-nav">お問い合わせ</a></div><button class="hamburger" aria-label="メニュー"><span></span><span></span><span></span></button></div></header>
<div class="nav-overlay"></div>
`;
const SITE_FAB = `<a href="contact.html" class="fab"><span>お問い合わせ</span></a>`;
const SITE_FOOTER = `
<footer><div class="container"><div class="footer-grid"><div><div class="footer-logo"><img src="${LOGO_URL}" alt="Enjin Payment Service"></div><p style="font-size:12px;opacity:0.6;">〒104-0061 東京都中央区銀5-13-16 8F</p></div><div class="footer-links"><h4>サービス</h4><ul><li><a href="services.html">ファクタリング</a></li><li><a href="services.html#salary">給与前払い</a></li></ul></div><div class="footer-links"><h4>会社情報</h4><ul><li><a href="about.html">私たちについて</a></li><li><a href="company.html">会社概要</a></li><li><a href="security.html">安心への取り組み</a></li><li><a href="privacy.html">プライバシーポリシー</a></li></ul></div><div class="footer-links"><h4>お問い合わせ</h4><ul><li><a href="contact.html">お問い合わせフォーム</a></li></ul></div></div><div class="footer-bottom"><p>&copy; 2026 Enjin Payment Service Co., Ltd. All Rights Reserved.</p></div></div></footer>
`;
document.addEventListener('DOMContentLoaded',()=>{const h=document.getElementById('site-header');const f=document.getElementById('site-footer');if(h)h.innerHTML=SITE_HEADER;if(f)f.innerHTML=SITE_FOOTER;if(!document.body.classList.contains('page-contact')){const fab=document.getElementById('site-fab');if(fab)fab.innerHTML=SITE_FAB;}const obs=new IntersectionObserver(e=>{e.forEach(en=>{if(en.isIntersecting){en.target.classList.add('active');obs.unobserve(en.target);}});},{threshold:0.1});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));const hb=document.querySelector('.hamburger');const nav=document.querySelector('nav');const ov=document.querySelector('.nav-overlay');if(hb&&nav&&ov){hb.addEventListener('click',()=>{hb.classList.toggle('active');nav.classList.toggle('open');ov.classList.toggle('active');document.body.style.overflow=nav.classList.contains('open')?'hidden':'';});ov.addEventListener('click',()=>{hb.classList.remove('active');nav.classList.remove('open');ov.classList.remove('active');document.body.style.overflow='';});}document.querySelectorAll('.faq-q').forEach(q=>{q.addEventListener('click',()=>{q.parentElement.classList.toggle('active');});});});
